# Generated by Django 5.2.8 on 2025-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/originals/', verbose_name='Изображение'),
        ),
    ]
